### ISSUE TITLE
Possible bug with UUID field/One-to-many?

### ISSUE THREAD

**Issue by minhphuong0401** [toluaina/pgsync#52]
PGSync version: 1.1.7

Postgres version: 12.4

Elasticsearch version: 7.7

Redis version: 5.0.7

Python version: 3.8.5

Problem Description: 
I have 2 simple tables as below

![ER diagram](https://user-images.githubusercontent.com/50161091/98187480-2225e980-1f65-11eb-933c-f6c5efe1d65f.png)

My schema.json is as below:
```
[
  {
    "database": "mydb",
    "index": "rating",
    "nodes": [
      {
        "table": "users",
        "schema": "public",
        "columns": [
          "user_id"
        ],
        "transform": {
          "mapping": {
            "user_id": {
              "type": "text"
            }
          }
        },
        "children": [
          {
            "table": "ratings",
            "schema": "public",
            "columns": [
              "movie_id"
            ],
            "transform": {
              "mapping": {
                "movie_id": {
                  "type": "text"
                }
              }
            },
            "relationship": {
              "variant": "object",
              "type": "one_to_many"
            }
          }
        ]
      }
    ]
  }
]
```

During the first run of bootstrap and pgsync --daemon, everything is ok.
But when I insert something into ratings table, I can see below error message and the inserted row is not synced to ElasticSearch

```
2020-11-05 01:40:47.809:ERROR:pgsync.sync: Exception rating_id
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/util/_collections.py", line 210, in __getattr__
    return self._data[key]
KeyError: 'rating_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pgsync/sync.py", line 634, in _sync
    self.query_builder.build_queries(node)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pgsync/querybuilder.py", line 789, in build_queries
    self._children(node)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pgsync/querybuilder.py", line 254, in _children
    getattr(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/util/_collections.py", line 212, in __getattr__
    raise AttributeError(key)
AttributeError: rating_id
2020-11-05 01:40:47.810:ERROR:pgsync.sync: Exception: rating_id
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/util/_collections.py", line 210, in __getattr__
    return self._data[key]
KeyError: 'rating_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pgsync/sync.py", line 703, in sync_payloads
    self.es.bulk(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pgsync/elastichelper.py", line 55, in bulk
    for _ in parallel_bulk(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 431, in parallel_bulk
    for result in pool.imap(
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 144, in _helper_reraises_exception
    raise ex
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 388, in _guarded_task_generation
    for i, x in enumerate(iterable):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 141, in _chunk_actions
    for action, data in actions:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pgsync/sync.py", line 634, in _sync
    self.query_builder.build_queries(node)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pgsync/querybuilder.py", line 789, in build_queries
    self._children(node)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pgsync/querybuilder.py", line 254, in _children
    getattr(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/util/_collections.py", line 212, in __getattr__
    raise AttributeError(key)
AttributeError: rating_id
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/util/_collections.py", line 210, in __getattr__
    return self._data[key]
KeyError: 'rating_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pgsync/sync.py", line 736, in poll_redis
    self.on_publish(payloads)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pgsync/sync.py", line 817, in on_publish
    self.sync_payloads(_payloads)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pgsync/sync.py", line 703, in sync_payloads
    self.es.bulk(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pgsync/elastichelper.py", line 55, in bulk
    for _ in parallel_bulk(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 431, in parallel_bulk
    for result in pool.imap(
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 144, in _helper_reraises_exception
    raise ex
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 388, in _guarded_task_generation
    for i, x in enumerate(iterable):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 141, in _chunk_actions
    for action, data in actions:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pgsync/sync.py", line 634, in _sync
    self.query_builder.build_queries(node)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pgsync/querybuilder.py", line 789, in build_queries
    self._children(node)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pgsync/querybuilder.py", line 254, in _children
    getattr(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/util/_collections.py", line 212, in __getattr__
    raise AttributeError(key)
AttributeError: rating_id
```

After that, if I run pgsync manually (without --daemon), I encounter this error:

```
 - users
    - ratings
 [==================================================] 100.0%
2020-11-05 01:41:26.995:ERROR:pgsync.sync: Exception: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type uuid: "'05911e41"
LINE 4: WHERE users_1.user_id = '''05911e41'
                                ^

[SQL: SELECT JSON_BUILD_ARRAY(anon_1._keys) AS "JSON_BUILD_ARRAY_1", JSON_BUILD_OBJECT(%(JSON_BUILD_OBJECT_2)s, users_1.user_id, %(JSON_BUILD_OBJECT_3)s, anon_1.ratings) AS "JSON_BUILD_OBJECT_1", users_1.user_id
FROM public.users AS users_1 LEFT OUTER JOIN (SELECT CAST(JSON_BUILD_OBJECT(%(JSON_BUILD_OBJECT_4)s, JSON_AGG(JSON_BUILD_OBJECT(%(JSON_BUILD_OBJECT_5)s, JSON_BUILD_ARRAY(ratings_1.rating_id)))) AS JSONB) AS _keys, JSON_AGG(JSON_BUILD_OBJECT(%(JSON_BUILD_OBJECT_6)s, ratings_1.movie_id)) AS ratings, ratings_1.user_id AS user_id
FROM public.ratings AS ratings_1 GROUP BY ratings_1.user_id) AS anon_1 ON anon_1.user_id = users_1.user_id
WHERE users_1.user_id = %(user_id_1)s]
[parameters: {'JSON_BUILD_OBJECT_2': 'user_id', 'JSON_BUILD_OBJECT_3': 'ratings', 'JSON_BUILD_OBJECT_4': 'ratings', 'JSON_BUILD_OBJECT_5': 'rating_id', 'JSON_BUILD_OBJECT_6': 'movie_id', 'user_id_1': "'05911e41"}]
(Background on this error at: http://sqlalche.me/e/13/9h9h)
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type uuid: "'05911e41"
LINE 4: WHERE users_1.user_id = '''05911e41'
                                ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pgsync/sync.py", line 703, in sync_payloads
    self.es.bulk(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pgsync/elastichelper.py", line 55, in bulk
    for _ in parallel_bulk(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 431, in parallel_bulk
    for result in pool.imap(
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 144, in _helper_reraises_exception
    raise ex
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 388, in _guarded_task_generation
    for i, x in enumerate(iterable):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 141, in _chunk_actions
    for action, data in actions:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pgsync/sync.py", line 642, in _sync
    row_count = self.query_count(node._subquery)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pgsync/base.py", line 637, in query_count
    return conn.execute(query).rowcount
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type uuid: "'05911e41"
LINE 4: WHERE users_1.user_id = '''05911e41'
                                ^

[SQL: SELECT JSON_BUILD_ARRAY(anon_1._keys) AS "JSON_BUILD_ARRAY_1", JSON_BUILD_OBJECT(%(JSON_BUILD_OBJECT_2)s, users_1.user_id, %(JSON_BUILD_OBJECT_3)s, anon_1.ratings) AS "JSON_BUILD_OBJECT_1", users_1.user_id
FROM public.users AS users_1 LEFT OUTER JOIN (SELECT CAST(JSON_BUILD_OBJECT(%(JSON_BUILD_OBJECT_4)s, JSON_AGG(JSON_BUILD_OBJECT(%(JSON_BUILD_OBJECT_5)s, JSON_BUILD_ARRAY(ratings_1.rating_id)))) AS JSONB) AS _keys, JSON_AGG(JSON_BUILD_OBJECT(%(JSON_BUILD_OBJECT_6)s, ratings_1.movie_id)) AS ratings, ratings_1.user_id AS user_id
FROM public.ratings AS ratings_1 GROUP BY ratings_1.user_id) AS anon_1 ON anon_1.user_id = users_1.user_id
WHERE users_1.user_id = %(user_id_1)s]
[parameters: {'JSON_BUILD_OBJECT_2': 'user_id', 'JSON_BUILD_OBJECT_3': 'ratings', 'JSON_BUILD_OBJECT_4': 'ratings', 'JSON_BUILD_OBJECT_5': 'rating_id', 'JSON_BUILD_OBJECT_6': 'movie_id', 'user_id_1': "'05911e41"}]
(Background on this error at: http://sqlalche.me/e/13/9h9h)
 0.0:0.0:0.19710540771484375 (0.20 sec)
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type uuid: "'05911e41"
LINE 4: WHERE users_1.user_id = '''05911e41'
                                ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/pgsync", line 7, in <module>
    sync.main()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pgsync/sync.py", line 955, in main
    sync.pull()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pgsync/sync.py", line 839, in pull
    self.logical_slot_changes(txmin=txmin, txmax=txmax)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pgsync/sync.py", line 239, in logical_slot_changes
    self.sync_payloads(payloads)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pgsync/sync.py", line 703, in sync_payloads
    self.es.bulk(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pgsync/elastichelper.py", line 55, in bulk
    for _ in parallel_bulk(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 431, in parallel_bulk
    for result in pool.imap(
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 144, in _helper_reraises_exception
    raise ex
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 388, in _guarded_task_generation
    for i, x in enumerate(iterable):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 141, in _chunk_actions
    for action, data in actions:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pgsync/sync.py", line 642, in _sync
    row_count = self.query_count(node._subquery)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pgsync/base.py", line 637, in query_count
    return conn.execute(query).rowcount
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type uuid: "'05911e41"
LINE 4: WHERE users_1.user_id = '''05911e41'
                                ^

[SQL: SELECT JSON_BUILD_ARRAY(anon_1._keys) AS "JSON_BUILD_ARRAY_1", JSON_BUILD_OBJECT(%(JSON_BUILD_OBJECT_2)s, users_1.user_id, %(JSON_BUILD_OBJECT_3)s, anon_1.ratings) AS "JSON_BUILD_OBJECT_1", users_1.user_id
FROM public.users AS users_1 LEFT OUTER JOIN (SELECT CAST(JSON_BUILD_OBJECT(%(JSON_BUILD_OBJECT_4)s, JSON_AGG(JSON_BUILD_OBJECT(%(JSON_BUILD_OBJECT_5)s, JSON_BUILD_ARRAY(ratings_1.rating_id)))) AS JSONB) AS _keys, JSON_AGG(JSON_BUILD_OBJECT(%(JSON_BUILD_OBJECT_6)s, ratings_1.movie_id)) AS ratings, ratings_1.user_id AS user_id
FROM public.ratings AS ratings_1 GROUP BY ratings_1.user_id) AS anon_1 ON anon_1.user_id = users_1.user_id
WHERE users_1.user_id = %(user_id_1)s]
[parameters: {'JSON_BUILD_OBJECT_2': 'user_id', 'JSON_BUILD_OBJECT_3': 'ratings', 'JSON_BUILD_OBJECT_4': 'ratings', 'JSON_BUILD_OBJECT_5': 'rating_id', 'JSON_BUILD_OBJECT_6': 'movie_id', 'user_id_1': "'05911e41"}]
(Background on this error at: http://sqlalche.me/e/13/9h9h)

```

Is this something to do with UUID primary key or one-to-many? Or did I do something wrong?

Error Message (if any): 

```


```

**Comment by toluaina** [comment]
You are totally right. I have fixed this and will be released in 1.1.18., Thanks for pointing this out!

**Comment by minhphuong0401** [comment]
Thanks! 
Do you have any ETA for 1.1.18?

**Comment by toluaina** [comment]
Yes, this has just been published. Correction this is now version 1.1.19

**Comment by minhphuong0401** [comment]
Thank you for your release! Indeed, it fixes the issue with one-to-many and UUID field.
However, in my above schema, when insert/update happens in the child table (rating), running pgsync both with/without daemon throws the warning:

`2020-11-06 03:48:34.880:WARNING:pgsync.sync: No filters supplied`

And the content of the child is not synced to ElasticSearch :(

**Comment by toluaina** [comment]
Can you try deleting the checkpoint file? In your case, it should be called **.mydb_rating**
And then run pgsync.

@minhphuong0401

**Comment by minhphuong0401** [comment]
@toluaina : Yes, I have tried to delete the checkpoint

Below is the log. When insert/update happens in parent table, it is synced correctly (100.0% line), but for child table, "WARNING:pgsync.sync: No filters supplied" could be seen, and it was not synced to ElasticSearch.
Rerun pgsync did not sync the data from child table as well

```
Polling db mydb: 0 cache items
Polling db mydb: 0 cache items
 [==================================================] 100.0%
Polling db mydb: 1 cache items
Polling db mydb: 1 cache items
Polling db mydb: 1 cache items
2020-11-07 00:01:08.088:WARNING:pgsync.sync: No filters supplied
2020-11-07 00:01:08.746:WARNING:pgsync.sync: No filters supplied
Polling db mydb: 5 cache items
2020-11-07 00:01:28.737:WARNING:pgsync.sync: No filters supplied
Polling db mydb: 7 cache items
2020-11-07 00:01:31.525:WARNING:pgsync.sync: No filters supplied
2020-11-07 00:01:31.539:WARNING:pgsync.sync: No filters supplied
Polling db mydb: 11 cache items
2020-11-07 00:01:44.730:WARNING:pgsync.sync: No filters supplied
2020-11-07 00:01:44.745:WARNING:pgsync.sync: No filters supplied
```

**Comment by toluaina** [comment]
@minhphuong0401 This should be fixed in release 1.1.20. Can you please try and confirm?

**Comment by minhphuong0401** [comment]
Hi @toluaina. Thanks for your response. 
Unfortunately, it still does not work :( 
When insert happens in child table, message "WARNING:pgsync.sync: No filters supplied" still shows and the change does not get sent to ElasticSearch

```
ubuntu@ip-xxx-xx-xx-x:~$ pgsync --version
Version: 1.1.20
ubuntu@ip-xxx-xx-xx-x:~$ rm -f .mydb_rating
ubuntu@ip-xxx-xx-xx-x:~$ curl -X DELETE http://localhost:9200/rating
{"acknowledged":true}
ubuntu@ip-xxx-xx-xx-x:~$ bootstrap --config ./ratings.json
 - users
    - ratings
ubuntu@ip-xxx-xx-xx-x:~$ pgsync --config ./ratings.json --daemon
 - users
    - ratings
 [==================================================] 100.0%
 0.0:0.0:0.5301239490509033 (0.53 sec)
Polling db mydb: 0 cache items
 [==================================================] 100.0%
Polling db mydb: 1 cache items
2020-11-09 21:24:03.114:WARNING:pgsync.sync: No filters supplied
Polling db mydb: 3 cache items
Polling db mydb: 3 cache items
Polling db mydb: 3 cache items
Polling db mydb: 3 cache items
2020-11-09 21:28:37.366:WARNING:pgsync.sync: No filters supplied
Polling db mydb: 5 cache items
Polling db mydb: 5 cache items
```

**Comment by toluaina** [comment]
You are absolutely right. I know the issue.

**Comment by minhphuong0401** [comment]
@toluaina : Great to hear that :)
Hopefully you can fix it soon :)

**Comment by minhphuong0401** [comment]
Hi @toluaina : do you have a chance to fix this issue?

**Comment by toluaina** [comment]
@minhphuong0401 
Sorry about this. I have resolved this in 1.1.21. You will need to bootstrap your database again.

**Comment by minhphuong0401** [comment]
It works great now! Thank you
